spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      properties.hibernate.temp.use_jdbc_metadata_defaults: false
  datasource:
    url: jdbc:postgresql://localhost:5432/myproject
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      platform: postgres

server:
  port: 9999