spring:
  jpa:
    database: POSTGRESQL
    hibernate:
      ddl-auto: update
    properties:
      properties.hibernate.temp.use_jdbc_metadata_defaults: false
    show-sql: true
  datasource:
    url: jdbc:postgresql://localhost:5432/myproject
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  sql:
    init:
      platform: postgres

server:
  port: 9999
  error: #для отображения ошибок при запросе
    include-message: always
    include-binding-errors: always